FROM docker.elastic.co/logstash/logstash:5.2.2
RUN rm /usr/share/logstash/pipeline/logstash.conf
COPY logstash.yml /usr/share/logstash/config/logstash.yml
COPY jvm.options /usr/share/logstash/config/jvm.options


